# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50)),
                ('bank_money', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ComBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.IntegerField()),
                ('amt', models.IntegerField()),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netIITD.Bank')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_name', models.CharField(max_length=50)),
                ('com_money', models.IntegerField()),
                ('mat1', models.IntegerField()),
                ('mat2', models.IntegerField()),
                ('mat3', models.IntegerField()),
                ('mat4', models.IntegerField()),
                ('mat5', models.IntegerField()),
                ('mat6', models.IntegerField()),
                ('mat7', models.IntegerField()),
                ('prod_units', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ComRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_1', to='netIITD.Company')),
                ('com_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_2', to='netIITD.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nation_name', models.CharField(max_length=50)),
                ('nation_money', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProdTrans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_unit', models.IntegerField()),
                ('prod_units', models.IntegerField()),
                ('com1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c1', to='netIITD.Company')),
                ('com2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c2', to='netIITD.Company')),
                ('prod_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netIITD.Material')),
            ],
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e1_type', models.IntegerField()),
                ('e1_id', models.IntegerField()),
                ('e2_type', models.IntegerField()),
                ('e2_id', models.IntegerField()),
                ('t_type', models.IntegerField()),
                ('amt', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='com_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netIITD.Material'),
        ),
        migrations.AddField(
            model_name='combank',
            name='com',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netIITD.Company'),
        ),
    ]
