# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netIITD', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdReq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_units', models.IntegerField()),
                ('tim', models.DateTimeField(auto_now=True)),
                ('com', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netIITD.Company')),
                ('out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netIITD.Material')),
            ],
        ),
    ]
