# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netIITD', '0002_prodreq'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='veto',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='nation',
            name='veto',
            field=models.IntegerField(default=0),
        ),
    ]
