# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netIITD', '0003_auto_20160920_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankNation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veto_part', models.IntegerField()),
                ('bank_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netIITD.Bank')),
            ],
        ),
        migrations.RemoveField(
            model_name='nation',
            name='veto',
        ),
        migrations.AddField(
            model_name='banknation',
            name='nation_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netIITD.Nation'),
        ),
    ]
