# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 18:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netIITD', '0004_auto_20160920_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banknation',
            old_name='bank_name',
            new_name='bank',
        ),
        migrations.RenameField(
            model_name='banknation',
            old_name='nation_name',
            new_name='nation',
        ),
    ]
