# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netIITD', '0006_nation_prod_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanTrans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ret', models.FloatField()),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netIITD.Bank')),
                ('com', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netIITD.Company')),
            ],
        ),
    ]
