# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netIITD', '0008_material_base_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComMat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amt', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='mat1',
        ),
        migrations.RemoveField(
            model_name='company',
            name='mat2',
        ),
        migrations.RemoveField(
            model_name='company',
            name='mat3',
        ),
        migrations.RemoveField(
            model_name='company',
            name='mat4',
        ),
        migrations.RemoveField(
            model_name='company',
            name='mat5',
        ),
        migrations.RemoveField(
            model_name='company',
            name='mat6',
        ),
        migrations.RemoveField(
            model_name='company',
            name='mat7',
        ),
        migrations.AddField(
            model_name='commat',
            name='com',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netIITD.Company'),
        ),
        migrations.AddField(
            model_name='commat',
            name='mat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netIITD.Material'),
        ),
    ]
