# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netIITD', '0009_auto_20160921_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bank_money',
            field=models.FloatField(default=50000),
        ),
        migrations.AlterField(
            model_name='banknation',
            name='veto_part',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='combank',
            name='amt',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='combank',
            name='interest',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='commat',
            name='amt',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='com_money',
            field=models.FloatField(default=1000.0),
        ),
        migrations.AlterField(
            model_name='company',
            name='prod_units',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='loantrans',
            name='ret',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='material',
            name='base_price',
            field=models.FloatField(default=1000),
        ),
        migrations.AlterField(
            model_name='nation',
            name='nation_money',
            field=models.FloatField(default=10000),
        ),
        migrations.AlterField(
            model_name='prodtrans',
            name='price_per_unit',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='amt',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='e1_type',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='e2_id',
            field=models.FloatField(),
        ),
    ]
