# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netIITD', '0010_auto_20160921_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurBankVeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veto', models.FloatField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PurProdHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_units', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_money',
            field=models.FloatField(default=600000),
        ),
        migrations.AlterField(
            model_name='bank',
            name='veto',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='commat',
            name='amt',
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name='company',
            name='com_money',
            field=models.FloatField(default=20000.0),
        ),
        migrations.AlterField(
            model_name='company',
            name='prod_units',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nation',
            name='nation_money',
            field=models.FloatField(default=100000),
        ),
        migrations.AddField(
            model_name='purprodhouse',
            name='com',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netIITD.Company'),
        ),
        migrations.AddField(
            model_name='purprodhouse',
            name='nation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netIITD.Nation'),
        ),
        migrations.AddField(
            model_name='purbankveto',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netIITD.Bank'),
        ),
        migrations.AddField(
            model_name='purbankveto',
            name='nation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netIITD.Nation'),
        ),
    ]
