# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netIITD', '0011_auto_20160924_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comrelation',
            name='com_1',
        ),
        migrations.RemoveField(
            model_name='comrelation',
            name='com_2',
        ),
        migrations.DeleteModel(
            name='Transfers',
        ),
        migrations.DeleteModel(
            name='ComRelation',
        ),
    ]
