# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netIITD', '0012_auto_20160924_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combank',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='combank',
            name='com',
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_money',
            field=models.FloatField(default=1500000),
        ),
        migrations.DeleteModel(
            name='ComBank',
        ),
    ]
